"""add relations to models

Revision ID: cdde90b31cdd
Revises: f14b9e712cd9
Create Date: 2024-07-18 12:12:22.416366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cdde90b31cdd"
down_revision: Union[str, None] = "f14b9e712cd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=True))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.VARCHAR(), nullable=True))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
